 const CartActionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    GET_ITEMS:'GET_ITEMS',
    INCREASE_COUNT:'INCREASE_COUNT',
    DECREASE_COUNT:'DECREASE_COUNT',
    REMOVE_ITEM:'REMOVE_ITEM',
    EMPTY_CART_START:'EMPTY_CART_START',
    EMPTY_CART_SUCCESS:'EMPTY_CART_SUCCESS'
}

export default CartActionTypes;